apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeshop-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeshop-app
  template:
    metadata:
      labels:
        app: kubeshop-app
    spec:
      containers:
        - name: kubeshop-app
          image: seuusuario/kubeshop-app:v1.0
          ports:
            - containerPort: 3000
